using System.Collections;
using Unity.VisualScripting;
using UnityEngine;

public class DayCycle : MonoBehaviour
{
    public static DayCycle instance;
    public string[] normalZombieList = { "Actisdato", "Kurniawan", "Pedroso" };
    public string[] specialZombieList = { "Parasite_Starkie", "Whiteclown_Hallin" };

    [SerializeField] private Light directionalLight;
    public float dayDuration = 24f;
    public float currentTime = 0f;

    // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿?ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private Color dayColor = new Color(1f, 1f, 1f);
    private Color nightColor = new Color(0.1f, 0.1f, 0.5f);

    private float dayIntensity = 1f;     // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?
    private float nightIntensity = 0.1f; // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?

    [SerializeField] private AudioClip _bgm;
    [SerializeField] private AudioClip day;
    [SerializeField] private AudioClip night;
    [SerializeField] private AudioClip dayClip;
    [SerializeField] private AudioClip nightClip;

    public bool isNight = false;           // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ È®ï¿½ï¿½
    private bool zombieSpawned = false;    // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ È®ï¿½ï¿½

    public int round = 10;

    void init()
    {
        round = 1;
        currentTime = 0f;

        // ï¿½ï¿½ï¿½Í°ï¿½ ï¿½ï¿½ï¿?ï¿½×¾ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½È¯ï¿½Ï´ï¿½ ï¿½Ìºï¿½Æ® ï¿½ï¿½ï¿½ï¿½
        ZombieManager.Instance.OnAllZombieDied += ChangeToDay;
    }

    void OnDisable()
    {

        // ï¿½Ìºï¿½Æ® ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
        ZombieManager.Instance.OnAllZombieDied -= ChangeToDay;
    }

    void Start()
    {
        if (instance == null)
        {
            instance = this;
        }
        AudioManager.Instance.PlayBGM(day);
        init();
    }

    void Update()
    {
        if (!isNight)
        {
            // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿?ï¿½ï¿½Å­ currentTimeï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Å´
            currentTime += Time.deltaTime;
            if (currentTime >= dayDuration)
            {
                isNight = true;
                AudioManager.Instance.PlayBGM(night);
                AudioManager.Instance.PlayClipOnce(nightClip);
                StartCoroutine(ChangeLightGradually(dayColor, nightColor, dayIntensity, nightIntensity));
            }
        }
    }

    private void ChangeToDay()
    {
        isNight = false;
        AudioManager.Instance.PlayBGM(day);
        AudioManager.Instance.PlayClipOnce(dayClip);
        // ï¿½Ú·ï¿½Æ¾ï¿½ï¿½ï¿½ï¿½ ï¿½ã³· ï¿½ï¿½È­ ï¿½ï¿½ï¿½ï¿½
        StartCoroutine(ChangeLightGradually(nightColor, dayColor, nightIntensity, dayIntensity));

        currentTime = 0f;
        zombieSpawned = false;
        round++;
        if(round > 10)
        {
            StartCoroutine(WaitGameFinish());
        }
    }

    private IEnumerator WaitGameFinish()
    {
        yield return new WaitForSeconds(3f);
        GameManager.instance.isClear = true;
    }

    // ï¿½ï¿½ï¿½ï¿½ï¿?ï¿½ï¿½ï¿?ï¿½Îµå·´ï¿½ï¿½ ï¿½ï¿½È¯ï¿½Ï´ï¿½ ï¿½Ú·ï¿½Æ¾
    private IEnumerator ChangeLightGradually(Color initialColor, Color targetColor, float initialIntensity, float targetIntensity)
    {
        float timeElapsed = 0f;
        float duration = 1f; // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿?ï¿½ï¿½È¯ï¿½ï¿½ ï¿½É¸ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½

        // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿?ï¿½ï¿½â¿¡ï¿½ï¿?ï¿½ï¿½Ç¥ ï¿½ï¿½ï¿½ï¿½ï¿?ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
        while (timeElapsed < duration)
        {
            directionalLight.color = Color.Lerp(initialColor, targetColor, timeElapsed / duration);
            directionalLight.intensity = Mathf.Lerp(initialIntensity, targetIntensity, timeElapsed / duration);
            timeElapsed += Time.deltaTime;
            yield return null; // ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?
        }

        // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Ç¥ ï¿½ï¿½ï¿½ï¿½ï¿?ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
        directionalLight.color = targetColor;
        directionalLight.intensity = targetIntensity;

        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½È¯ï¿½ï¿½ ï¿½Ï·ï¿½Ç¾ï¿½ï¿½ï¿?ï¿½ï¿½ ï¿½ï¿½ï¿½Í¸ï¿½ ï¿½ï¿½ï¿½ï¿½
        if (isNight && !zombieSpawned)
        {
            // ï¿½ï¿½ï¿½ï¿½ 5ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
            for (int i = 0; i < 6 + 1 * round; i++)  // ï¿½ï¿½ï¿½ï¿½ 5ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
            {
                ZombieManager.Instance.SpawnZombie(normalZombieList[Random.Range(0, 3)]);

                // special zombie spawn
                if(Random.Range(0, 130) < 45)
                {
                    ZombieManager.Instance.SpawnZombie(specialZombieList[0]);
                }

                if (Random.Range(0, 150) < 20)
                {
                    ZombieManager.Instance.SpawnZombie(specialZombieList[1]);
                }
            }
            zombieSpawned = true; // ï¿½ï¿½ï¿½Í°ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ç¾ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?
        }
    }
}
